coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1%
    patch:
      default:
        target: 70%

ignore:
  - "src/market/*"  # Lower priority for initial pass
  - "test/*"
  - "docs/*"
  - "src/python-helpers/*"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
