FROM python:3.11-slim

ARG UPLOADER_CAPABILITIES_URL=https://letovocorp.ru/letovo-api/auth/amiuploader
ENV UPLOADER_CAPABILITIES_URL=${UPLOADER_CAPABILITIES_URL}

WORKDIR /app

COPY . .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8880

CMD ["python3", "flask_uploader.py"]
