CREATE TABLE IF NOT EXISTS camp_dates (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    CONSTRAINT camp_dates_dates_order CHECK (start_date <= end_date),
    CONSTRAINT camp_dates_no_overlap EXCLUDE USING gist (daterange(start_date, end_date, '[]') WITH &&)
);
