version: '3.8'

services:
    letovo-server:
        image: ghcr.io/letovo-dev/letovo-server:latest
        container_name: letovo-server
        restart: unless-stopped
        network_mode: "host"
        volumes:
          - /mnt/server-media:/app/pages
          - /mnt/server-configs:/app/configs
        labels:
          - "com.centurylinklabs.watchtower.enable=true"

    watchtower:
        image: containrrr/watchtower
        restart: unless-stopped
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 300 --cleanup --include-restarting --label-enable --registry-auth

    letovo-front:
        image: letovo-front:latest
        container_name: letovo-front
        restart: unless-stopped
        depends_on:
          - letovo-server
        ports:
          - "3000:3000"
        env_file:
          - /home/zahar/letovo/front-env

    letovo-flask-uploader:
        image: flask-uploader:latest
        container_name: flask-uploader
        restart: unless-stopped
        volumes:
          - /mnt/server-media:/app/pages
        ports:
          - "8880:8880"

    keycloak:
        image: quay.io/keycloak/keycloak:26.0
        command: ["start"]                    # без лишней экзотики
        environment:
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://172.17.0.1:5432/keycloak?sslmode=disable
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: keycloak

            KC_PROXY: edge
            KC_HTTP_RELATIVE_PATH: /auth-center
            KC_HOSTNAME_URL: https://letovocorp.ru/auth-center
            KC_HOSTNAME_ADMIN_URL: https://letovocorp.ru/auth-center
            KC_HOSTNAME_STRICT: "false"

            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
          - "8081:8080"
